- name: Simple Debug Script
  hosts: all
  gather_facts: yes

  tasks:
   - debug:
       msg: "net add bridge bridge {{ node[inventory_hostname].switching.bridge | join (" ") }}"

#   - debug:
#       msg: "{{ node[inventory_hostname].routing.ospf.neighbors }}"

#   - debug:
#       msg: "{{ node[inventory_hostname].routing.lo | regex_replace('/32')}}"

#   - debug:
#       msg: "{{ item.value.ip }}"
#     with_dict:
#       - "{{ node[inventory_hostname]['routing']['svi'] }}"
