- name: Configure CLAG and VRR Switches
  hosts: switches
  become: yes
  gather_facts: yes
  tasks:

  - name: Initial Switch and Management VRF setup
    nclu:
      commit: true
      description: "Initial Management VRF setup"
      commands:
        - add interface eth0 vrf mgmt
        - add hostname "{{ inventory_hostname }}"

  - name: Deploy Bond Interfaces
    nclu:
      commit: true
      description: "Deploy Interfaces"
      template: |
         add interface "{{ item }}"
    with_items:
      - "{{ node[inventory_hostname].ports }}"
    when: item.value | regex_search('^bond')

  - name: Deploy Interfaces
    nclu:
      commit: true
      description: "Deploy Interfaces"
      template: |
          add interface "{{ item }}"
    with_items:
      - "{{ node[inventory_hostname].ports }}"

  - name: Deploy VLANs
    nclu:
      commit: true
      description: "Deploy VLANs"
      template: |
         add vlan "{{ item }}"
    with_items:
       - "{{ node[inventory_hostname].switching.vlans }}"

  - name: Deploy Bridging configuration
    nclu:
      commit: true
      description: "Deploy Bridging configuration"
      commands:
          - add bridge bridge "{{ node[inventory_hostname].switching.bridge | join (" ") }}"

  - name: Deploy CLAG Unnumbered configuration
    nclu:
        commit: true
        description: "Deploy CLAG Unnumbered configuration"
        commands:
            - add interface peerlink.4094 ip address {{ node[inventory_hostname].mlag.address }}
            - add interface peerlink.4094 clag peer-ip {{ node[inventory_hostname].mlag.peerip }}
            - add interface peerlink.4094 clag backup-ip {{ node[inventory_hostname].mlag.backupip }} vrf mgmt
            - add interface peerlink.4094 clag sys-mac {{ node[inventory_hostname].mlag.sysmac }}
            - add interface peerlink.4094 clag priority {{ node[inventory_hostname].mlag.priority }}

  - name: Deploy VRR and SVI configuration
    nclu:
        commit: true
        description: "Deploy VRR and SVI configuration"
        template: |
           add vlan {{ item.value.vlan }} ip address {{ item.value.ip }}
           add vlan {{ item.value.vlan }} ip address-virtual {{ item.value.vrrp.mac }} {{ item.value.vrrp.ip }}
    with_dict:
      - "{{ node[inventory_hostname].routing.svi }}"

#  - name: Deploy BGP Unnumbered Interfaces
#    nclu:
#        commit: true
#        description: "Deploy BGP Unnumbered Interfaces"
#        template: |
#           add bgp neighbor {{ item }} remote-as external
#    with_items:
#      - "{{ node[inventory_hostname].routing.bgp.underlay.external.peers }}"
#    when: node[inventory_hostname].routing.bgp.underlay.external.peers is defined

  - name: Reload Interfaces
    command: ifreload -a
